/*global define*/
/*
define({
    // INSTALL_TEXT : '安装',
    // UNLIKE_TEXT : '换一个',
    // SD_CARD_TEXT : 'SD 卡',
    // PHONE_TEXT : '手机',
    // NON_DESCRIPTION_TEXT : '没有描述',
    DELETE_TEXT : '删除',
    // EXPORT_TEXT : '导出',
    REFRESH_TEXT : '刷新',
    OK : '确定',
    CANCEL : '取消',
    DIALOG_TIP : '提示',
    // COMPLETE_TEXT : '完成',
    SHARE : '分享',
    // LOGIN : '登录',
    // RETRY_TEXT : '重试',
    // SAVE_TEXT : '保存',
    // RESELECT_FILE_TEXT : '重新选择文件',
    VIEW_PIC : '查看大图',
    YES : '是',
    NO : '否',
    // IGNORE : '忽略',
    NEXT_STEP : '下一步',
    PRE_STEP : '上一步',
    // AD : '推广',
    REFRESH_ERROR : '刷新失败。',
    // CONFIRM : '确认无误，继续',
    // CONTINUE : '继续',
    // SKIP : '跳过',
    // BACKUP : '备份',
    VIEW : '查看',
    RECOMMEND_YES : '是（推荐）',
    OPEN : '打开',
    // CLOSE : '关闭',
    WANDOUJIA_TOPIC : ' #豌豆荚#',

    SHARE_TO : '分享到：',
    SHARE_TO_FACEBOOK_FAILD : '分享到 Facebook 失败',
    SHARE_TO_FACEBOOK : '分享到 Facebook',
    SHARE_WIDGET_TITLE : '分享 {1}',
    SHARE_WIDGET_TITLE_2 : '吐槽 {1}',
    SHARE_WIDGET_INPUT_COUNT_TEXT : '还可以输入 {1} 字',
    SHARE_WIDGET_INPUT_OVER_COUNT_TEXT : '字数超过 {1} 个',
    SHARE_WIDGET_CONTENT_TIP_TEXT : '豌豆荚会自动附上截图和来源',
    SHARE_WIDGET_SENT_TEXT : '分享成功',
    SHARE_WIDGET_FAILED_TEXT : '分享失败',
    SHARE_WIDGET_COOKIE_EXPIRED_TEXT : '分享失败，请重新登录',
    SHARE_WIDGET_PREVIEW_PIC : '图片预览',
    SHARE_WIDGET_VIEW_FROM_PC_ERROR : '很抱歉，查看大图失败',
    SHARE_WIDGET_PIC_LIMIT_SIZE_TIP : '抱歉，您分享的图片大于 {1}MB',
    SHARE_WIDGET_ERROR_NEED_SELECT_PLATFORM : '抱歉，您需要选择要分享到的社交网络',
    SHARE_WIDGET_SHARE_TIP : '说点什么吧？',
    SHARE_WIDGET_EXIT_TEXT : '退出登录',
    // LOGIN_FAILED : '登录失败',
    SHARE_CONTENT_TYPE_SCREENSHOT : '截屏',
    SHARE_CONTENT_TYPE_PHOTO : '照片',
    SHARE_CONTENT_TYPE_WELCOME : '豌豆荚',
    SHARE_CONTENT_TYPE_APP : '应用',
    // SHARE_CONTENT_TYPE_DORAEMON_EXTENSION : '百宝袋扩展',
    FACEBOOK_MESSAGE_FROM : ' 来自我的{1}。',
    // SHARE_DORAEMON_CATEGORY_OTHER : '其他',
    // SHARE_DORAEMON_CATEGORY_INTEREST : '有趣儿',
    // SHARE_DORAEMON_CATEGORY_DEFAULT : '有趣儿的内容',

    SHARE_BINDED : '已绑定',
    SHARE_TO_SINA : '绑定新浪微博',
    SHARE_TO_QQ : '绑定腾讯微博',
    SHARE_TO_QZONE : '绑定Qzone',
    SHARE_TO_RENREN : '绑定人人网',

    // SELECTOR_DESCRIPTION_TEXT : '已选 {1} 个，共 {2} 个',

    TODAY : '今天',
    YESTODAY : '昨天',
    // THE_DAY_BEFORE_YESTODAY : '前天',
    // MONTH : '月',
    // DAY : '日',
    // YEAR : '年',

    HOUR : '{1} 小时',
    // MINUTE : '{1} 分钟',
    // SECOND : '{1} 秒',

    // SD_MOUNT_TIP_TEXT : '豌豆荚检测不到 SD 卡，请在手机上取消挂载 SD 卡。',
    NO_SD_CARD_TIP_TEXT : '豌豆荚检测到您的手机上没有 SD 卡',
    // NO_SD_CARD_SIZE_TEXT : '暂时无法读取 SD 卡数据',

    // IMPORT_LABEL : '导入',
    // EXPORT_LABEL : '导出',
    CANCEL_IMPORT_TEXT : '导入操作已被取消',
    CANCEL_EXPORT_TEXT : '导出操作已被取消',

    // CANCEL_IN_PROGRESS : '正在取消操作，请稍侯...',

    SD_CAPACITY_TIP : '您的 SD 卡快满了！',
    PHONE_CAPACITY_TIP : '手机空间不够了！',
    SD_CAPACITY_ACTION : '打开 SD 卡管理',
    PHONE_CAPACITY_ACTION : '一键移动应用到 SD 卡',

    SEND_MAIL_FAILD : '非常抱歉，发送邮件失败',
    // ZIP_PACKAGE_ERROR : '抱歉，打包出错',
    // ZIP_PACKAGE_SUCCESS : '打包成功，打包文件在您刚上传文件的同级目录',

    LOAD_MORE : '加载更多',
    LOADING : '加载中...',
    LOAD_FAILD : '加载失败'
});
*/
