/*global define*/
define({
    OPEN_DOWNLOAD_FOLDER : '打开下载文件夹',
    RUNNING_STATUS : '已下载 {1}，{2}/s',
    PUSHING_STATUS : '已传输 {1}, {2}/s',
    PAUSE_STATUS : '已下载 {1}，已暂停',
    PUSH_PAUSE_STATUS : '已传输 {1}，已暂停',
    WAITING_DOWNLOAD : '等待下载',
    WAITING_PUSHING : '等待传输',
    WAITING_INSTALL : '等待安装',
    UNINSTALL_THEN_INSTALL : '卸载后安装',
    CHANGE_INSTALL_LOCATION : '修改安装位置',
    MANAGE_APP : '管理应用',
    INSTALL_TO_DEVICE : '安装到内存',
    MANAGE_SD : '管理 SD 卡',
    TASK_NAME : '任务名称',
    SIZE : '大小',
    PROGRESS : '进度',
    RUNNING_COUNT : '{1} 项任务正在进行',
    FAILED_COUNT : '{1} 项任务失败',
    WATING_PUSH_COUNT : '{1} 项任务待传输',
    NO_TASK_RUNNING : '没有正在进行的任务',
    HOW_TO_CONNECT_URL : 'http://help.wandoujia.com/entries/401079-2-0',
    UNKNOWN : '未知',
    CONFIRM_DELETE : '确定要删除这个任务吗？',
    CONFIRM_DELETE_BATCH : '确定要删除选中的任务吗？',
    DELET_APK_ALSO : '同时把下载文件移到回收站',
    DELETE_TITLE : '删除下载任务',
    RUNNING_COUNT_TIP : '{1} 项进行中',
    ERROR_COUNT_TIP : '{1} 项失败',
    COMPLETE_COUNT_TIP : '{1} 项完成',
    DEVICE_NOT_CONNECT : '没有连接手机',
    DEVICE_NOT_CONNECT_TIP : '豌豆荚检测到您没有连接手机，任务在连接后将自动传输到手机上。',
    CONFIRM_ON_DEVICE_TIP : '您正在使用 Wi-Fi 模式连接手机，需要在手机上确认才能完成安装。',
    CONFIRM_ON_DEVICE_MIUI_V5_TIP : '您的手机使用的是 MIUI 系统，需要在手机上确认才能完成安装。',
    DEVICE_DISCONNECT : '连接已断开',
    DEVICE_DISCONNECT_TIP : '豌豆荚检测到您的手机已经断开连接，任务下载完成后将保存在电脑上，下次连接时将自动传输到手机上。',
    OFFLINE_TASK_TIP : '从您的手机上获取到 {1} 个零流量下载任务',
    OUT_OF_SPACE_WARN : '硬盘空间预警',
    OUT_OF_SPACE_TIP : '豌豆荚检测到您的硬盘空间已不足 500M。<br />建议您重新设置下载位置。',
    MODIFY_STORAGE_DISK : '修改下载位置',
    NOT_ENOUGH_SPACE_WARN : '硬盘空间不足',
    NOT_ENOUGH_SPACE_TIP : '豌豆荚检测到您的硬盘空间已满，请重新设置下载位置。',

    STOPPED : '已停止',
    DOWNLOAD_FAILED : '下载失败',
    NO_SPACE : '硬盘已满',
    INSTALLING : '正在安装',
    CONFIRM_ON_DEVICE : '请在手机上完成安装',
    UNKNOWN_ERROR : '未知错误',
    TASK_ADDED : '任务已添加',
    PROCESSING : '任务进行中',
    PUSHING : '正在传输 ',
    PARSING_VIDEO_URL : '正在解析 MP4 视频地址',
    PARSING_VIDEO_URL_SUCCESS : '解析 MP4 视频地址成功',
    MERGE_VIDEO : '正在合并 MP4 视频',
    MERGE_VIDEO_SUCCESS : '合并 MP4 视频成功',
    LOOK_OVER : '查看',
    UNKNOWN_NAME : '未知名称',


    CACHE_SIZE : '节省了 {1} 流量',
    ADD_TASK_TIP : '添加了 {1} 项任务',
    FINISH_TASK_TIP : '{1} 项任务已完成',

    DELETE_TASK : '删除应用',
    CONTINUE_INSTALL : '继续安装',


    /* Install failed reasons */

    SCANNING : '正在进行安全扫描',
    SCAN_PASS : '已通过安全扫描',
    SCAN_FAILED : '未通过安全扫描',


    SET_AS_WALL_PAPER : '设为手机壁纸',
    START_UNZIPPING : '开始解压',
    UNZIPING : '正在解压...',
    UNZIP_COMPLETE : '解压成功',
    UNZIP_FAILED : '解压失败',

    HOW_TO_CONNECT : '如何连接',
    EMPTY_LIST : '没有任务',


    WAITING_RESTORE_APP_DATA : '等待恢复应用数据',
    PROCESSING_RESTORE_APP_DATA : '正在恢复应用数据',
});
