/*global define*/
define({
    ADD_LOCAL_VIDEO_TEXT : '添加本地视频',
    NO_VIDEOS_TEXT : '您的手机中还没有视频呢。',
    DELETE_TIP : '确定要删除选中的 {1} 个视频？',
    VIDEO_DELETE_ERROR_TEXT : '对不起，以下视频删除失败：',
    VIDEO_EXPORT_ERROR_TEXT : '对不起，以下视频导出失败：',
    VIDEO_IMPORT_ERROR_TEXT : '对不起，以下视频文件导入失败：',
    DELETE_PROGRESS_TEXT : '正在删除视频，请稍候...',
    DELETE_SUCCESS_TEXT : '成功删除 {1} 个视频。',
    DELETE_VIDEO_ERROR : '删除视频失败',
    IMPORT_PROGRESS_TEXT : '正在导入视频，请稍候...',
    IMPORT_SUCCESS_TEXT : '成功导入 {1} 个视频。',
    IMPORT_UNCONNECT_TEXT : '很抱歉，您的手机连接已断开，无法导入视频。',
    IMPORT_FAILED_TEXT : '很抱歉，导入视频失败。',
    EXPORT_PROGRESS_TEXT : '正在导出视频，请稍候...',
    EXPORT_SUCCESS_TEXT : '成功导出 {1} 个视频。',
    VIDEO_NAME : '视频名称',
    VIDEO_FORMAT : '视频格式',
    VIDEO_SIZE : '视频大小',
    VIDEO_ADDOR_GRID_TIP : '您还未添加视频',
    FILE_SELECTOR_DESCRIPTION : '选择视频文件或包含视频文件的文件夹，支持多选',
    ADD_VIDEO_LOADING : '正在添加视频，请稍候...',
    VIDEO_SUPPORT_TIP : 'Android 系统默认仅支持 .avi .3gp .mp4 .m4v 四种格式。如果需要导入其它格式视频，请使用 <span class="link button-manage-sd">SD 卡管理</span>。'
});
