 language: node_js
 node_js:
   - "0.10"
 before_script:
   - npm install -g grunt-cli
   - gem install compass
   - npm install
 notifications:
   email:
     - wangye.zhao@wandoujia.com
     - lixiaopeng@wandoujia.com
     - netputer@wandoujia.com
   slack:
     rooms:
       - wandoulabs:F5pNeT3U0YJ3sOPLgq7HYwPh#frontend-team
