/*global define*/
/*
define({
    // INSTALL_TEXT : 'Install',
    // UNLIKE_TEXT : 'Next',
    // SD_CARD_TEXT : 'SD Card',
    // PHONE_TEXT : 'Internal',
    // NON_DESCRIPTION_TEXT : 'No description',
    DELETE_TEXT : 'Delete',
    // EXPORT_TEXT : 'Export',
    REFRESH_TEXT : 'Refresh',
    OK : 'OK',
    CANCEL : 'Cancel',
    DIALOG_TIP : 'Notification',
    // COMPLETE_TEXT : 'Done ',
    SHARE : 'Share',
    // LOGIN : 'Login',
    // RETRY_TEXT : 'Retry',
    // SAVE_TEXT : 'Save',
    // RESELECT_FILE_TEXT : 'Re-select file',
    VIEW_PIC : 'View larger image',
    YES : 'Yes',
    NO : 'No',
    // IGNORE : 'Ignore',
    NEXT_STEP : 'Next',
    PRE_STEP : 'Previous',
    // AD : 'Ad',
    REFRESH_ERROR : 'Reload failed',
    // CONFIRM : 'Verification completed, continue',
    // CONTINUE : 'Continue',
    // SKIP : 'Skip',
    // BACKUP : 'Backup',
    VIEW : 'View',
    RECOMMEND_YES : 'Yes (recommended)',
    OPEN : 'Open',
    // CLOSE : 'Close',
    WANDOUJIA_TOPIC : '#SnapPea# ',

    SHARE_TO : 'Share to:',
    SHARE_TO_FACEBOOK_FAILD : 'Share to Facebook failed',
    SHARE_TO_FACEBOOK : 'Share to Facebook',
    SHARE_WIDGET_TITLE : 'Share to {1}',
    SHARE_WIDGET_TITLE_2 : 'Share {1}',
    SHARE_WIDGET_INPUT_COUNT_TEXT : '{1}/120 characters',
    SHARE_WIDGET_INPUT_OVER_COUNT_TEXT : 'More than {1} characters, message will be shortened.',
    SHARE_WIDGET_CONTENT_TIP_TEXT : 'Image will be attached to your post',
    SHARE_WIDGET_SENT_TEXT : 'Shared to Facebook',
    SHARE_WIDGET_FAILED_TEXT : 'Failed to share to Facebook',
    SHARE_WIDGET_COOKIE_EXPIRED_TEXT : 'Faile to share, please login again',
    SHARE_WIDGET_PREVIEW_PIC : 'Image preview',
    SHARE_WIDGET_VIEW_FROM_PC_ERROR : 'Sorry, failed to display larger image',
    SHARE_WIDGET_PIC_LIMIT_SIZE_TIP : 'Sorry, you can\'t share pictures larger than {1} MB',
    SHARE_WIDGET_ERROR_NEED_SELECT_PLATFORM : 'Sorry, you can\'t share content without selecting social network',
    SHARE_WIDGET_SHARE_TIP : 'Share something',
    SHARE_WIDGET_EXIT_TEXT : 'Sign out',
    // LOGIN_FAILED : 'Login failed',
    SHARE_CONTENT_TYPE_SCREENSHOT : 'Screenshot',
    SHARE_CONTENT_TYPE_PHOTO : 'Photo',
    SHARE_CONTENT_TYPE_WELCOME : 'SnapPea',
    SHARE_CONTENT_TYPE_APP : 'App',
    // SHARE_CONTENT_TYPE_DORAEMON_EXTENSION : 'Doraemon Extension',
    FACEBOOK_MESSAGE_FROM : ' From my {1}.',
    // SHARE_DORAEMON_CATEGORY_OTHER : 'Other',
    // SHARE_DORAEMON_CATEGORY_INTEREST : 'Interesting',
    // SHARE_DORAEMON_CATEGORY_DEFAULT : 'Interesting stuff',

    // SELECTOR_DESCRIPTION_TEXT : '{1} of {2} selected',

    SHARE_BINDED : 'Already linked',
    SHARE_TO_SINA : 'Linked to Sina Weibo',
    SHARE_TO_QQ : 'Linked to Tencent Weibo',
    SHARE_TO_QZONE : 'Linked to Qzone',
    SHARE_TO_RENREN : 'Linked to Renren',

    TODAY : 'Today',
    YESTODAY : 'Yesterday',
    // THE_DAY_BEFORE_YESTODAY : '2 Days ago',
    // MONTH : 'Month',
    // DAY : 'Day',
    // YEAR : 'Year',

    HOUR : '{1} hour(s)',
    // MINUTE : '{1} minute(s)',
    // SECOND : '{1} second(s)',

    // SD_MOUNT_TIP_TEXT : 'SnapPea didn\'t detect a SD card. Please exit USB storage mode on your device.',
    NO_SD_CARD_TIP_TEXT : 'No SD card detected',
    // NO_SD_CARD_SIZE_TEXT : 'temporarily unable to read SD card',

    // IMPORT_LABEL : 'Import',
    // EXPORT_LABEL : 'Export',
    CANCEL_IMPORT_TEXT : 'Import canceled',
    CANCEL_EXPORT_TEXT : 'Export canceled',

    // CANCEL_IN_PROGRESS : 'Canceling operation, please wait...',

    SD_CAPACITY_TIP : 'Your SD card is almost full!',
    PHONE_CAPACITY_TIP : 'Not enough internal storage space',
    SD_CAPACITY_ACTION : 'Open your SD card manager',
    PHONE_CAPACITY_ACTION : 'Move all your apps to your SD card in one-click',

    SEND_MAIL_FAILD : 'Failed to send email',
    // ZIP_PACKAGE_ERROR : 'Sorry, failed to export',
    // ZIP_PACKAGE_SUCCESS : 'Exported file to the same folder',

    LOAD_MORE : 'Loading more...',
    LOADING : 'Loading...',
    LOAD_FAILD : 'Failed to load'
});
*/
