/*global define*/
define({
    ADD_LAOCEL_PHOTO_LABEL : 'Import pictures',
    FILE_SELECTOR_DESCRIPTION : 'Select pictures from a file or folder',
    PREVIEW_TEXT : 'Preview',
    PICTURE_NAME : 'Name',
    PICTURE_FORMAT : 'Format',
    PICTURE_SIZE : 'Size',
    SLIDE_PLAY_TEXT : 'Slideshow',
    DELETE_TIP : 'Delete {1} picture(s)? ',
    IMPORT_PROGRESS_TEXT : 'Importing pictures, please wait...',
    IMPORT_SUCCESS_TEXT : 'Imported {1} picture(s)',
    EXPORT_PROGRESS_TEXT : 'Exporting picture, please wait...',
    EXPORT_SUCCESS_TEXT : 'Exported {1} picture(s)',
    PHOTO_ADDOR_COUNT_TEXT : '{1} of {2} selected. Free space on SD card: {3}',
    PHOTO_ADDOR_GRID_TIP : 'Import a picture here',
    GET_PHOTOS_ERROR : 'Failed to access picture',
    DELETE_PHOTO_ERROR : 'Failed to access picture',
    DELETE_PROGRESS_TEXT : 'Deleting pictures, please wait...',
    DELETE_SUCCESS_TEXT : 'Deleted {1} picture(s)',
    EMPTY_PHONE_LIST : 'Import a picture here!',
    EMPTY_LIBRARY_LIST : 'Import a picture here!',
    EXPORT_FAILED_TEXT : 'Export failed',
    LOADING_BIGPICTURE_TEXT : 'Loading picture...',
    SLIDES_STOP_TEXT : 'Pause',
    SLIDES_AUTO_TEXT : 'Auto-play',
    WALLPAPER_SETTING_SUCCESS_TEXT : 'Set as wallpaper!',
    WALLPAPER_SETTING_TEXT : 'Setting wallpaper...',
    WALLPAPER_SETTING_FAILED_TEXT : 'Sorry, operation failed. ',
    PHOTO_DELETE_ERROR_TEXT : 'Sorry, failed to delete the following picture(s): ',
    PHOTO_EXPORT_ERROR_TEXT : 'Sorry, failed to export the following picture(s): ',
    PHOTO_IMPORT_ERROR_TEXT : 'Sorry, failed to import the following picture(s): ',

    THREAD_DISPLAY_SHOW : 'Expand',
    THREAD_DISPLAY_HIDDEN : 'Hide',

    GET_PHOTO_FROM_PC_ERROR : 'Failed to get pictures from your computer',
    ROTATE_RIGHT : 'Rotate right',
    ROTATE_LEFT : 'Rotate left',
    NEXT : 'Next',
    PREV : 'Previous',
    SLIDE_SHOW : 'Slideshow',
    SET_AS_WALLPAPER : 'Set as wallpaper',
    BACKUP_MY_PHOTOS : 'Automatically backup my photos',
    UPLOADING_PHOTOS : 'Uploading photos',
    PHOTO_BACKUP_AUTO : 'Upload completed',
    PHOTO_SYNC : '<p>Do you want to automatically upload to your gallery？</p><p>Take a picture on your device, and it\'ll upload to: <a href="#" class="go-photo-sync">{1}</a> From there you can view or share your photos anytime!</p>',
    PHOTO_SYNC_CLOSED : 'Turned off photo sync | ',
    PHOTO_SYNC_OPENED : 'Turned on photo sync | ',
    TIP_CLOSE_PHOTO_SYNC : 'Are you sure you want to turn off photo sync?',
    CLOSE_PHOTO_SYNC : 'Turn off photo sync',
    SHARE_WALLPAPER : 'Wallpaper set! Share out your new wallpaper?'
});
