/*global define*/
define({
    OPEN_DOWNLOAD_FOLDER : 'Downloads folder',
    RUNNING_STATUS : '{1}, {2}/s',
    PUSHING_STATUS : '{1} transfering, {2}/s',
    PAUSE_STATUS : '{1}, paused',
    PUSH_PAUSE_STATUS : '{1} transfering，now paused',
    WAITING_DOWNLOAD : 'Download queued',
    WAITING_PUSHING : 'Transfer queued',
    WAITING_INSTALL : 'Install queued',
    UNINSTALL_THEN_INSTALL : 'Uninstall & reinstall',
    CHANGE_INSTALL_LOCATION : 'Settings',
    MANAGE_APP : 'Manage',
    INSTALL_TO_DEVICE : 'Install to internal storage',
    MANAGE_SD : 'Manage SD card',
    TASK_NAME : 'Task',
    SIZE : 'Size',
    PROGRESS : 'Status',
    RUNNING_COUNT : '{1} tasks...',
    FAILED_COUNT : '{1} task(s) failed',
    WATING_PUSH_COUNT : '{1} items to push',
    NO_TASK_RUNNING : 'No tasks in progress',
    HOW_TO_CONNECT_URL : 'http://snappea.zendesk.com/forums/20791302-connecting-your-device',
    UNKNOWN : 'Unknown',
    CONFIRM_DELETE : 'Remove this item?',
    CONFIRM_DELETE_BATCH : 'Remove these items?',
    DELET_APK_ALSO : ' Also move files to Recycle Bin?',
    DELETE_TITLE : 'Remove downloaded items',
    RUNNING_COUNT_TIP : '{1} items in progress',
    ERROR_COUNT_TIP : '{1} items failed',
    COMPLETE_COUNT_TIP : '{1} items completed',
    DEVICE_NOT_CONNECT : 'No device connected',
    DEVICE_NOT_CONNECT_TIP : 'You haven\'t connected a device. Downloads will automatically transfer the next time you connect.',
    CONFIRM_ON_DEVICE_TIP : 'You\'re using Wi-Fi to connect, which requires you to confirm the install on your device.',
    CONFIRM_ON_DEVICE_MIUI_V5_TIP : 'You\' using MIUI, which requires you to confirm the install on your device.',
    DEVICE_DISCONNECT : 'Device disconnected',
    DEVICE_DISCONNECT_TIP : 'Device disconnected. Downloads will automatically transfer the next time you connect.',
    OFFLINE_TASK_TIP : '{1} zero-data mode download task(s) initiated from your phone',
    OUT_OF_SPACE_WARN : 'Warning: Running out of hard drive space',
    OUT_OF_SPACE_TIP : 'You have less than 500M of hard drive space remaining.<br />You could set a new download folder',
    MODIFY_STORAGE_DISK : 'Set download folder',
    NOT_ENOUGH_SPACE_WARN : 'Hard drive space is insufficient',
    NOT_ENOUGH_SPACE_TIP : 'Your hard drive space is already full. Please set set a new download folder.',

    STOPPED : 'Paused',
    DOWNLOAD_FAILED : 'Download failed',
    NO_SPACE : 'Disk full',
    INSTALLING : 'Installing...',
    CONFIRM_ON_DEVICE : 'Finish install on your device',
    UNKNOWN_ERROR : 'Unknown error',
    TASK_ADDED : 'Task added',
    PROCESSING : 'Processing...',
    PUSHING : 'Transfering to your device...',
    PARSING_VIDEO_URL : 'Parsing mp4 video URLs...',
    PARSING_VIDEO_URL_SUCCESS : 'Parsing mp4 video URLs completed',
    MERGE_VIDEO : 'Merging mp4 videos',
    MERGE_VIDEO_SUCCESS : 'Merging mp4 videos completed',
    UNKNOWN_NAME : 'Unknown name',


    CACHE_SIZE : 'You\'ve saved: {1}',
    ADD_TASK_TIP : '{1} task added',
    FINISH_TASK_TIP : '{1} task completed',

    DELETE_TASK : 'Delete task',
    CONTINUE_INSTALL : 'Resume install',


    /* Install failed reasons */

    SCANNING : 'Security scan in progress...',
    SCAN_PASS : 'Safe! Passed security scan.',
    SCAN_FAILED : 'Failed security scan.',


    SET_AS_WALL_PAPER : 'Set as wallpaper',
    START_UNZIPPING : 'Unzipping...',
    UNZIPING : 'Unzipping...',
    UNZIP_COMPLETE : 'Unzip completed',
    UNZIP_FAILED : 'Unzip failed',

    HOW_TO_CONNECT : 'Connection help',
    EMPTY_LIST : 'No tasks in progress',


    WAITING_RESTORE_APP_DATA : 'Waiting to restore app data',
    PROCESSING_RESTORE_APP_DATA : 'Restoring app data...',
});
