/*global define*/
define({
    ADD_LOCAL_VIDEO_TEXT : 'Import videos',
    NO_VIDEOS_TEXT : 'Import a video here!',
    DELETE_TIP : 'Delete the {1} selected video(s)?',
    VIDEO_DELETE_ERROR_TEXT : 'Failed to delete the following video(s): ',
    VIDEO_EXPORT_ERROR_TEXT : 'Failed to export the following video(s): ',
    VIDEO_IMPORT_ERROR_TEXT : 'Failed to import the following video(s): ',
    DELETE_PROGRESS_TEXT : 'Deleting video(s), please wait...',
    DELETE_SUCCESS_TEXT : 'Deleted {1} video(s)',
    DELETE_VIDEO_ERROR : 'Failed to delete video(s)',
    IMPORT_PROGRESS_TEXT : 'Importing video, please wait...',
    IMPORT_SUCCESS_TEXT : 'Imported {1} video(s)',
    IMPORT_UNCONNECT_TEXT : 'Please reconnect your device and try to import the video again',
    IMPORT_FAILED_TEXT : 'Failed to import video(s)',
    EXPORT_PROGRESS_TEXT : 'Exporting video, please wait...',
    EXPORT_SUCCESS_TEXT : 'Exported {1} video(s)',
    VIDEO_NAME : 'Name',
    VIDEO_FORMAT : 'Format',
    VIDEO_SIZE : 'Size',
    VIDEO_ADDOR_GRID_TIP : 'Import a video here',
    FILE_SELECTOR_DESCRIPTION : 'Select videos from a file or folder',
    ADD_VIDEO_LOADING : 'Importing video, please wait...',
    VIDEO_SUPPORT_TIP : 'Formats supported: .avi .3gp .mp4 and .m4v To manage other formats, use your <span class="link button-manage-sd">SD card</span>.'
});
