/*global define*/
define({
    WELCOME_PAGE_SHOT : 'Share welcome screen to Facebook',
    WELCOME_PAGE_SHOT_FOR_FACEBOOK : 'Share screenshot to Facebook',
    SCREEN_SHOT_CLIPBOARD_SUCCESS : 'Copied to clipboard',
    SCREEN_SHOT_FAILD : 'Failed to mirror device',
    SCREEN_SHOT_CANCELD : 'Cancel mirroring device',

    SCREEN_SHOT_TEXT : 'Capture',
    SCREEN_SHOT_SAVE_TO_FILE : 'Save',
    SCREEN_SHOT_SAVE_TO_CLIPBOARD : 'Copy to clipboard',
    SCREEN_SHOT_WITH_WRAP : 'Normal',
    SCEEN_SHOT_WITHOUT_WRAP : 'Screen only',
    SAVE_PATH_FOR_SCREENSHOT : 'Edit screenshots folder...',
    SAVE_PATH_FOR_SCREENSHOT_TIP : 'Screenshot taken! Save all future screenshots to the same folder? ',
    SAVE_SCREEN_SHOT_SUCCESS : 'Screenshot taken',

    PLAY_BTN_TEXT : 'Mirror',
    PAUSE_BTN_TEXT : 'Pause',
    SEND_WEIBO_BTN_TEXT : 'Share to Facebook',
    REFRESH_BTN_TEXT : 'Refresh',
    FULLSCREEN_BTN_TEXT : 'Full-screen',

    TOOL_BACKUP : 'Backup',
    TOOL_RECOVERY : 'Restore',
    TOOL_SD : 'SD Card',

    MANAGE_SD_UNCONNECT : 'Your device is not connected, unable to manage files',
    MANAGE_SD_ERROR : 'Oh no, unable to manage files',
    HAS_NO_SD_CARD : 'No SD card detected in your device',
    MANAGE_SD_INTERNET : 'Unfortunately you can\'t manage your SD card over the Internet.',

    EDIT_RING : 'Sound Settings',

    AUTO_BACKUP : 'Last auto backup: {1}',
    SHOW_FILE : 'Open',
    TIP_IN_OPEN_FILE1 : 'Sorry, SnapPea can\'t find that backup file',
    TIP_IN_OPEN_FILE2 : 'Possible causes of error: <br /> - File was accidentally deleted <br /> - File path was changed',
    START_AUTO_BACKUP : 'Auto-backup in progress',
    AUTO_BACKUP_SMS_COMPLETE : 'Messages completed',
    AUTO_BACKUP_CONTACTS_COMPLETE : 'Contacts completed',
    AUTO_BACKUP_APP_COMPLETE : 'Apps completed',
    AUTO_BACKUP_PHOTO_COMPLETE : 'Pictures completed',
    AUTO_BACKUP_COMPLETE : 'Auto-backup complete',
    AUTO_BACKUP_TIP_IN_PROGRESS : 'Auto-backup in progress...',
    AUTO_BACKUP_TIP_COMPLETE : 'Last auto-backup：{1}',

    CONNECT_UR_PHONE : 'Connect your device',
    CONNECTION_TIP : 'SnapPea lets you install apps, send messages, and manage your contacts, pictures, and music. Let\'s get started!',
    CONNECT_PHONE : 'Connect',

    FLASH_TIP_TITLE : 'Flash your device?',
    FLASH_TIP_DESC : 'SnapPea can help you restore your data right now!',

    NEW_IA_QUESTIONNAIRE : 'Hey, do you like the new SnapPea？<span class="link button-like" style="margin-left: 15px">Like</span><span class="link button-unlike"  style="margin-left: 15px">Don\'t Like</span><span class="link button-whatever"  style="margin-left: 15px">No opinion</span>',
    CLOSE_AUTO_START : 'To help you manage your phone, SnapPea will automatically open when you connect your phone. You can turn this off in <span class="link button-setup">Settings</span>',

    GUIDE_BIND : 'Link phone',
    GUIDE_BIND_NOW : 'Link phone now',
    GUIDE_BIND_DESC : 'After linking, SnapPea will auto-backup your contacts, messages, and photos. It makes it easy to restore and easy to connect. If this isn\'t your computer, don\'t link!',
    GUIDE_BIND_SUCCESS : 'Congrats, {1} phone is linked. SnapPea will auto-backup your <strong>contacts, messages, and photos</strong>',
    GUIDE_CLOUD_BACKUP : 'Cloud backup',
    GUIDE_CLOUD_BACKUP_OPEN : 'Turn on cloud backup',
    GUIDE_CLOUD_BACKUP_DESC : 'After linking, SnapPea will auto-backup your contacts, messages, and photos. If this isn\'t your computer, don\'t link!',
    GUIDE_CLOUD_BACKUP_SUCCESS : 'Congrats, you\'ve already registered and turned on cloud backups.',
    GUIDE_REG : 'Register for SnapPea',
    GUIDE_REG_DESC : 'To turn on cloud albums you first have to register an account',
    GUIDE_REG_NOW : 'Register now',
    GUIDE_REG_ACCOUNT : 'Account',
    GUIDE_REG_ACCOUNT_PLACEHOLDER : 'Please use your phone number or email address',
    GUIDE_REG_ACCOUNT_WARN : '您输入的好像不是一个邮箱/手机号',
    GUIDE_REG_PASSWORD : '密码',
    GUIDE_REG_PASSWORD_PLACEHOLDER : '最少 6 位数字或字符',
    GUIDE_REG_PASSWORD_WARN : '请输入密码，密码长度应该大于 6 个字符',
    GUIDE_REG_PSW_VERIFY_PLACEHOLDER : '再次输入密码',
    GUIDE_REG_PSW_VERIFY_WARN : '两次输入的密码不一致',
    GUIDE_REG_NICKNAME : '昵称',
    GUIDE_REG_NICKNAME_WARN : '昵称不能少于一个字符',
    GUIDE_REG_CAPTCHA : '验证码',
    GUIDE_REG_PRAVICY : '同意 <a target="_default" href="#">最终用户条款</a>',
    GUIDE_REG_LOGIN_WITH_ACCOUNT : '已有账号登陆',
    GUIDE_REG_LOGIN_WITH_SNS : '合作账号登陆',
    GUIDE_REG_LOGIN_AND_BACKUP : '登陆后开启云备份',
    GUIDE_XIBAIBAI_START : '马上开洗',
    GUIDE_XIBAIBAI_TIP2 :　'豌豆洗白白会帮您找出这些应用，并替换成官方版或没有广告的版本。',
    GUIDE_XIBAIBAI_TIP3 : '立即使用豌豆洗白白享受放心应用的乐趣吧！',
    GUIDE_STARTER_INSTALL_ALL : 'Install all',
    GUIDE_STARTER_TITLE : 'Must install apps',
    GUIDE_STARTER_TIP : 'Not many apps on your phone. You should try some of these star apps.',
    GUIDE_STARTER_APP_TIP : '{1} installations · {2}% positive reviews<br />{3}',
    GUIDE_TIPS : 'Tips',
    GUIDE_TIPS_TIP : 'More tips about SnapPea!',
    GUIDE_TIPS_READ_ALL : 'OK, got it!',
    GUIDE_TIPS_OPEN : 'View',
    GUIDE_SUGGESTION : 'View more',
    GUIDE_SUGGESTION_TIP : 'There\'s more content for you to discover!',
    GUIDE_SUGGESTION_READ_ALL : 'I\'m done'
});
