/*global define*/
define({
    WELCOME_PAGE_SHOT : 'Share welcome screen to Facebook',
    WELCOME_PAGE_SHOT_FOR_FACEBOOK : 'Share screenshot to Facebook',
    SCREEN_SHOT_CLIPBOARD_SUCCESS : 'Copied to clipboard',
    SCREEN_SHOT_FAILD : 'Failed to mirror device',
    SCREEN_SHOT_CANCELD : 'Cancel mirroring device',

    SCREEN_SHOT_TEXT : 'Capture',
    SCREEN_SHOT_SAVE_TO_FILE : 'Save',
    SCREEN_SHOT_SAVE_TO_CLIPBOARD : 'Copy to clipboard',
    SCREEN_SHOT_WITH_WRAP : 'Normal',
    SCEEN_SHOT_WITHOUT_WRAP : 'Screen only',
    SAVE_PATH_FOR_SCREENSHOT : 'Edit screenshots folder...',
    SAVE_PATH_FOR_SCREENSHOT_TIP : 'Screenshot taken! Save all future screenshots to the same folder? ',
    SAVE_SCREEN_SHOT_SUCCESS : 'Screenshot taken',

    PLAY_BTN_TEXT : 'Mirror',
    PAUSE_BTN_TEXT : 'Pause',
    SEND_WEIBO_BTN_TEXT : 'Share to Facebook',
    REFRESH_BTN_TEXT : 'Refresh',
    FULLSCREEN_BTN_TEXT : 'Full-screen',

    TOOL_BACKUP : 'Backup',
    TOOL_RECOVERY : 'Restore',
    TOOL_SD : 'SD Card',

    MANAGE_SD_UNCONNECT : 'Your device is not connected, unable to manage files',
    MANAGE_SD_ERROR : 'Oh no, unable to manage files',
    HAS_NO_SD_CARD : 'No SD card detected in your device',
    MANAGE_SD_INTERNET : 'Unfortunately you can\'t manage your SD card over the Internet.',

    EDIT_RING : 'Sound Settings',

    AUTO_BACKUP : 'Last auto backup: {1}',
    SHOW_FILE : 'Open',
    TIP_IN_OPEN_FILE1 : 'Sorry, SnapPea can\'t find that backup file',
    TIP_IN_OPEN_FILE2 : 'Possible causes of error: <br /> - File was accidentally deleted <br /> - File path was changed',
    START_AUTO_BACKUP : 'Auto-backup in progress',
    AUTO_BACKUP_SMS_COMPLETE : 'Messages completed',
    AUTO_BACKUP_CONTACTS_COMPLETE : 'Contacts completed',
    AUTO_BACKUP_APP_COMPLETE : 'Apps completed',
    AUTO_BACKUP_PHOTO_COMPLETE : 'Pictures completed',
    AUTO_BACKUP_COMPLETE : 'Auto-backup complete',
    AUTO_BACKUP_TIP_IN_PROGRESS : 'Auto-backup in progress...',
    AUTO_BACKUP_TIP_COMPLETE : 'Last auto-backup：{1}',

    CONNECT_UR_PHONE : 'Connect your device',
    CONNECTION_TIP : 'SnapPea lets you install apps, send messages, and manage your contacts, pictures, and music. Let\'s get started!',
    CONNECT_PHONE : 'Connect',

    FLASH_TIP_TITLE : 'Flash your device?',
    FLASH_TIP_DESC : 'SnapPea can help you restore your data right now!',

    NEW_IA_QUESTIONNAIRE : '偷偷问一下，您喜欢豌豆荚新的样子吗？<span class="link button-like" style="margin-left: 15px">喜欢</span><span class="link button-unlike"  style="margin-left: 15px">不喜欢</span><span class="link button-whatever"  style="margin-left: 15px">没感觉</span>',
    CLOSE_AUTO_START : '为方便您管理手机，豌豆荚在您手机连上电脑后会自动启动。如果您不希望自动启动，可以在 <span class="link button-setup">设置</span> 中关闭',

    GUIDE_BIND : '绑定手机',
    GUIDE_BIND_NOW : '立即绑定',
    GUIDE_BIND_DESC : '绑定自己的手机后，豌豆荚会帮助您自动备份手机联系人、短信、照片和应用，方便您即时恢复，还可以 Wi-Fi 下自动连接手机，无需手动操作。如果您使用的不是自己的电脑和手机，请不要绑定！',
    GUIDE_BIND_SUCCESS : '恭喜，你已经成功绑定 {1}，豌豆荚会自动帮您备份此手机的 <strong>联系人、短信、照片和应用。</strong>',
    GUIDE_CLOUD_BACKUP : '云备份',
    GUIDE_CLOUD_BACKUP_OPEN : '开启云备份',
    GUIDE_CLOUD_BACKUP_DESC : '绑定自己的手机后，豌豆荚会帮助您自动备份手机联系人、短信、照片和应用，方便您即时恢复，还可以 Wi-Fi 下自动连接手机，无需手动操作。如果您使用的不是自己的电脑和手机，请不要绑定！',
    GUIDE_CLOUD_BACKUP_SUCCESS : '恭喜，您已经成功注册并开启了云备份。',
    GUIDE_REG : '注册豌豆荚',
    GUIDE_REG_DESC : '开启云备份请先注册豌豆荚账号',
    GUIDE_REG_NOW : '马上注册',
    GUIDE_REG_ACCOUNT : '账号',
    GUIDE_REG_ACCOUNT_PLACEHOLDER : '请使用手机号码或邮箱',
    GUIDE_REG_ACCOUNT_WARN : '您输入的好像不是一个邮箱/手机号',
    GUIDE_REG_PASSWORD : '密码',
    GUIDE_REG_PASSWORD_PLACEHOLDER : '最少 6 位数字或字符',
    GUIDE_REG_PASSWORD_WARN : '请输入密码，密码长度应该大于 6 个字符',
    GUIDE_REG_PSW_VERIFY_PLACEHOLDER : '再次输入密码',
    GUIDE_REG_PSW_VERIFY_WARN : '两次输入的密码不一致',
    GUIDE_REG_NICKNAME : '昵称',
    GUIDE_REG_NICKNAME_WARN : '昵称不能少于一个字符',
    GUIDE_REG_CAPTCHA : '验证码',
    GUIDE_REG_PRAVICY : '同意 <a target="_default" href="#">最终用户条款</a>',
    GUIDE_REG_LOGIN_WITH_ACCOUNT : '已有账号登陆',
    GUIDE_REG_LOGIN_WITH_SNS : '合作账号登陆',
    GUIDE_REG_LOGIN_AND_BACKUP : '登陆后开启云备份',
    GUIDE_XIBAIBAI_START : '马上开洗',
    GUIDE_XIBAIBAI_TIP2 :　'豌豆洗白白会帮您找出这些应用，并替换成官方版或没有广告的版本。',
    GUIDE_XIBAIBAI_TIP3 : '立即使用豌豆洗白白享受放心应用的乐趣吧！',
    GUIDE_STARTER_INSTALL_ALL : '一键安装',
    GUIDE_STARTER_TITLE : '必备应用',
    GUIDE_STARTER_TIP : '您的手机应用有点少，给您的设备安装优质必备应用吧。',
    GUIDE_STARTER_APP_TIP : '{1}人安装 · {2}% 好评率<br />{3}',
    GUIDE_TIPS : '小技巧',
    GUIDE_TIPS_TIP : '更多关于豌豆荚的小技巧，一般人我不告诉他！',
    GUIDE_TIPS_READ_ALL : '都知道了',
    GUIDE_TIPS_OPEN : '查看',
    GUIDE_SUGGESTION : '更多精彩',
    GUIDE_SUGGESTION_TIP : '丰富多彩的内容站期待您的发现。',
    GUIDE_SUGGESTION_READ_ALL : '我看完了'
});
